### ISSUE TITLE
Course 5 ─ Deep Learning and Reinforcement Learning/Week 1 ─ Introduction to Neural Networks/Week 1 Quiz 3 ─ End of Module Quiz issue

### ISSUE THREAD

**Issue by johnfelipe** [AhmedIsmailKhalid/IBM-Machine-Learning#2]
this is repeated, is same like

/Course 5 ─ Deep Learning and Reinforcement Learning/Week 1 ─ Introduction to Neural Networks/Week 1 Quiz 2 ─ Activation Functions

pls update and solve asap

**Comment by AhmedIsmailKhalid** [comment]
The course content has changed since I took the course. I am no longer enrolled in the course and hence cannot update with the latest one!
