### ISSUE TITLE
Course 5 ─ Deep Learning and Reinforcement Learning/Week 4 ─ Recurrent Neural Networks and Long-Short Term Memory Networks/Week 4 Quiz 3 ─ End of Module Quiz issued

### ISSUE THREAD

**Issue by johnfelipe** [AhmedIsmailKhalid/IBM-Machine-Learning#3]
Course 5 ─ Deep Learning and Reinforcement Learning/Week 4 ─ Recurrent Neural Networks and Long-Short Term Memory Networks/Week 4 Quiz 3 ─ End of Module Quiz

is not end of module quiz is repeated, pls update asap

**Comment by AhmedIsmailKhalid** [comment]
The quiz material has changed since I took the course. I am no longer enrolled in the course with the newer version hence I cannot update with the new one!
